apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-ingestion-rolebinding
  namespace: data-ingestion
subjects:
- kind: ServiceAccount
  name: data-ingestion-sa
  namespace: data-ingestion
roleRef:
  kind: Role
  name: data-ingestion-role
  apiGroup: rbac.authorization.k8s.io
